module.exports = async function handler(req, res) {
  const data = {
    "zona": "NORTE",
    "planes_max": [
      {
        "nombre": "COLMENA MAX NORTE PF 1264040",
        "pb_uf": 1.85,
        "pb_clp": 73489,
        "zona": "NORTE",
        "tipo": "COLMENA MAX",
        "hospitalizacion": "50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago. \n40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú).",
        "coberturas_grupos": {},
        "consulta_preferente": "50% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n40% Clínica BUPA Antofagasta.",
        "consulta_le": "0.35",
        "tope_consulta_le_uf": 0.35,
        "tope_anual_uf": 7500.0
      },
    {
      "nombre": "COLMENA MAX NORTE PF 1264050",
      "pb_uf": 1.96,
      "pb_clp": 77859,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "0.37",
      "tope_consulta_le_uf": 0.37,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1264060",
      "pb_uf": 2.08,
      "pb_clp": 82626,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "0.39",
      "tope_consulta_le_uf": 0.39,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1265050",
      "pb_uf": 2.18,
      "pb_clp": 86598,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "0.4600000000000001",
      "tope_consulta_le_uf": 0.46,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1264070",
      "pb_uf": 2.19,
      "pb_clp": 86995,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "0.41000000000000003",
      "tope_consulta_le_uf": 0.41,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1264080",
      "pb_uf": 2.27,
      "pb_clp": 90173,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 50% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 40% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
      "consulta_le": "0.43000000000000005",
      "tope_consulta_le_uf": 0.43,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1265060",
      "pb_uf": 2.29,
      "pb_clp": 90968,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "0.4900000000000001",
      "tope_consulta_le_uf": 0.49,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1266050",
      "pb_uf": 2.33,
      "pb_clp": 92557,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "0.5800000000000002",
      "tope_consulta_le_uf": 0.58,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1265070",
      "pb_uf": 2.41,
      "pb_clp": 95735,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "0.5200000000000001",
      "tope_consulta_le_uf": 0.52,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1266060",
      "pb_uf": 2.48,
      "pb_clp": 98515,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "0.6100000000000002",
      "tope_consulta_le_uf": 0.61,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1265080",
      "pb_uf": 2.52,
      "pb_clp": 100104,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 60% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 50% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
      "consulta_le": "0.5500000000000002",
      "tope_consulta_le_uf": 0.55,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1267050",
      "pb_uf": 2.53,
      "pb_clp": 100502,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "0.7000000000000003",
      "tope_consulta_le_uf": 0.7,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1266070",
      "pb_uf": 2.61,
      "pb_clp": 103679,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "0.6400000000000002",
      "tope_consulta_le_uf": 0.64,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1267060",
      "pb_uf": 2.67,
      "pb_clp": 106063,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "0.7300000000000003",
      "tope_consulta_le_uf": 0.73,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1266080",
      "pb_uf": 2.72,
      "pb_clp": 108049,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 70% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 60% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
      "consulta_le": "0.6700000000000003",
      "tope_consulta_le_uf": 0.67,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1267070",
      "pb_uf": 2.81,
      "pb_clp": 111624,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "0.7600000000000003",
      "tope_consulta_le_uf": 0.76,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1267080",
      "pb_uf": 2.92,
      "pb_clp": 115994,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 80% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 70% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
      "consulta_le": "0.7900000000000004",
      "tope_consulta_le_uf": 0.79,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1268050",
      "pb_uf": 2.96,
      "pb_clp": 117583,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "0.8200000000000004",
      "tope_consulta_le_uf": 0.82,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1268060",
      "pb_uf": 3.1,
      "pb_clp": 123144,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "0.8500000000000004",
      "tope_consulta_le_uf": 0.85,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1269050",
      "pb_uf": 3.19,
      "pb_clp": 126719,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "0.9400000000000005",
      "tope_consulta_le_uf": 0.94,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1268070",
      "pb_uf": 3.26,
      "pb_clp": 129500,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "0.8800000000000004",
      "tope_consulta_le_uf": 0.88,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1269060",
      "pb_uf": 3.35,
      "pb_clp": 133075,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "0.9700000000000005",
      "tope_consulta_le_uf": 0.97,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 12610050",
      "pb_uf": 3.35,
      "pb_clp": 133075,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 100% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "60% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n50% Clínica BUPA Antofagasta.",
      "consulta_le": "1.0600000000000005",
      "tope_consulta_le_uf": 1.06,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1268080",
      "pb_uf": 3.37,
      "pb_clp": 133870,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 90% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 80% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
      "consulta_le": "0.9100000000000005",
      "tope_consulta_le_uf": 0.91,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1269070",
      "pb_uf": 3.5,
      "pb_clp": 139034,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "1.0000000000000004",
      "tope_consulta_le_uf": 1.0,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 12610060",
      "pb_uf": 3.5,
      "pb_clp": 139034,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 100% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "70% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n60% Clínica BUPA Antofagasta.",
      "consulta_le": "1.0900000000000005",
      "tope_consulta_le_uf": 1.09,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 1269080",
      "pb_uf": 3.63,
      "pb_clp": 144198,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago.\n90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 90% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
      "consulta_le": "1.0300000000000005",
      "tope_consulta_le_uf": 1.03,
      "tope_anual_uf": 7500.0
    },
    {
      "nombre": "COLMENA MAX NORTE PF 12610070",
      "pb_uf": 3.66,
      "pb_clp": 145390,
      "zona": "NORTE",
      "tipo": "COLMENA MAX",
      "hospitalizacion": "100% BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 100% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
      "coberturas_grupos": {},
      "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.\n70% Clínica BUPA Antofagasta.",
      "consulta_le": "1.1200000000000006",
      "tope_consulta_le_uf": 1.12,
      "tope_anual_uf": 7500.0
    },
     {
        "nombre": "COLMENA MAX NORTE PF 12610080",
        "pb_uf": 3.78,
        "pb_clp": 150157,
        "zona": "NORTE",
        "tipo": "COLMENA MAX",
        "hospitalizacion": "100% BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago, Clínica Indisa (Providencia y Maipú). 100% Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá, Clínica Dávila Recoleta, Clínica Dávila Vespucio, Clínica BUPA Santiago 100% BUPA Antofagasta, Clínica Indisa (Providencia y Maipú)",
        "coberturas_grupos": {},
        "consulta_preferente": "80% Centros Médicos RedSalud, Integramédica, Clínica BUPA Antofagasta, Clínica La Portada ACHS Salud, Clínica Atacama ACHS Salud, Clínica Andes Salud El Loa, Clínica Tarapacá.",
        "consulta_le": "1.1500000000000006",
        "tope_consulta_le_uf": 1.15,
        "tope_anual_uf": 7500.0
      }
    ],
    "total": 29,
    "uf_valor": 39724.12
  };
  
  res.status(200).json(data);
}
